#!/usr/bin/env php
<?php

// Autoload de composer
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    die("Need to install dependencies with composer");
}

if (isset($argv[1])) {
    (new \Horyzone\Sim\Init())->console($argv[1]);
} else {
    (new \Horyzone\Sim\Init())->console();
}
