home:
  methode: get
  path: /
  controller: App\Controllers\HomeController
  fonction: getHome
  middlewares: [alert]

home_post:
  methode: post
  path: /
  controller: App\Controllers\HomeController
  fonction: postHome

# Example route with routerjs
hello:
  methode: get
  path: /hello/{name}
  controller: App\Controllers\HomeController
  fonction: getHome
